#!/bin/bash
MICSRC=" alsa_input.usb-045e_Microsoft_LifeChat_LX-3000-00-default.analog-mono"
pacmd set-default-source$MICSRC > /dev/null 2>&1
INPUTSRC=`pactl stat | grep Source | awk -F":" '{print $2}'`
if [ -z $1 ]; then
	AMSG="Out."
else
	AMSG=$1
fi
if [ "$INPUTSRC" == "$MICSRC" ]; then
	echo "Activate ScreenSaver..."
	dbus-send --session --dest=org.gnome.ScreenSaver --type=method_call --print-reply --reply-timeout=20000 /org/gnome/ScreenSaver org.gnome.ScreenSaver.SetActive boolean:true
	purple-remote setstatus?status=away\&message="$AMSG (Camera Activated @`date -u +%Y%m%d\T%H%M\Z`)"
	echo "Activate Motion Detection in 5 seconds..."
	sleep 5
	qdbus org.kde.amarok /Player org.freedesktop.MediaPlayer.Pause
	motion
	purple-remote setstatus?status=available\&message=
	qdbus org.kde.amarok /Player org.freedesktop.MediaPlayer.Play
	if [ "`ls ~/Ubuntu\ One/Webcam/ | wc -l`" -gt "21" ]; then
		zenity --error --text="You have over 7 events that require review. Get off your fucking ass."
	fi
else
	echo "DEFAULT SOURCE ($INPUTSRC) DOES NOT MATCH $MICSRC"
	echo "ABORTING."
	if [ -x /usr/bin/zenity ]; then
		zenity --error --text="DEFAULT SOURCE ($INPUTSRC) DOES NOT MATCH $MICSRC"
	else
		echo "Could not launch zenity. Hopefully you are paying attention to this."
	fi
fi
